name: analyse-semgrep

on:
  push:
    branches:
    - 'main'

jobs:
  semgrep_scan:
    name: semgrep/ci
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Analyse semgrep
        run: source /home/runner-admin/semgrep/bin/activate | semgrep --config "p/rust" .    
