name: analyse-semgrep

on:
  push:
    branches:
    - 'main'

jobs:
  semgrep_scan:
    name: semgrep/ci
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name : change source
        run: source /home/runner-admin/semgrep/bin/activate
      - name: Analyse semgrep 1
        run: semgrep --config "p/rust" .  
      - name: Analyse semgrep 2
        run: semgrep --config "p/owasp-top-ten" --lang rust .
