name: analyse-semgrep

on:
  push:
    branches:
    - 'main'

jobs:
 semgrep_scan_rust:
    name: semgrep_rust
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: fmt-2
        run: cargo fmt
      - name: fmt
        run: cargo fmt --check
      - name : change source
        run: source /home/runner-admin/semgrep/bin/activate
      - name: Analyse semgrep 1
        run: semgrep --config "p/rust" .
 Semgrep_all:
    needs: semgrep_scan_rust
    name: semgrep_all
    runs-on: self-hosted
    continue-on-error: true
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name : change source
        run: source /home/runner-admin/semgrep/bin/activate
      - name: test all
        run: semgrep ci --config auto
 clippy:
    needs: Semgrep_all
    name: clippy-code
    runs-on: self-hosted
    continue-on-error: true
    steps:
      - name: Clippy-analyse
        run: cargo clippy
 audit:
    needs: clippy
    name: audit-code
    runs-on: self-hosted
    continue-on-error: true
    steps:
      - name: cargo-audit
        run: cargo audit
 
